# This is a basic workflow to help you get started with Actions

name: Client WorkFlow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Build, Deploy to S3 Bucket
    runs-on: [ubuntu-latest]
    env:
      working-directory: ./website

    strategy:
      matrix:
        node-version: [12.16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
        node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn install
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: yarn build
        working-directory: ${{ env.working-directory }}

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: s3://newdrawapp
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_REGION: "us-west-1"
          SOURCE_DIR: "client/build/"
